[project]
name = "greenova"
version = "0.1.0"
description = "Environmental management system"
authors = [
    {name = "Adrian Gallo", email = "agallo@enveng-group.com.au"},
]
requires-python = ">=3.13.2"
license = {text = "AGPL-3.0"}

[tool.black]
line-length = 88
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/tests/data/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --doctest-modules"
testpaths = [
    "tests",
]
python_files = ["test_*.py", "*_test.py"]
pythonpath = ["."]

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[tool.djlint]
profile = "django"
indent = 2
max_line_length = 100
use_gitignore = true
blank_line_before_tag = "load,extends,include,block"
close_void_tags = true
format_css = true
format_js = true
